name: grad
description: School management software.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  badges: ^2.0.1
  collection: ^1.15.0
  connectivity_plus: ^2.2.0
  get: ^4.6.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.2
  flutter_svg: ^1.0.3
  hexcolor: ^2.0.5
  http: ^0.13.1
  jiffy: ^5.0.0
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+4
  cached_network_image: ^3.2.0
  flutter_feather_icons: ^2.0.0+1
  table_calendar: ^3.0.3
  timelines: ^0.1.0
  get_storage: ^2.0.3
  php_serializer: ^1.1.0
  image_picker: ^0.8.4+11
  onesignal_flutter: ^3.3.0
  timeago: ^3.2.2
  flutter_slidable: ^1.2.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  stream_chat_flutter: ^4.1.0
  firebase_messaging: ^11.2.15
  get_it: ^7.2.0
  firebase_core: ^1.15.0
  flutter_local_notifications: ^9.4.1

  dropdown_button2: ^1.4.0
  json_serializable: ^6.2.0
  flutter_downloader: ^1.7.3
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/sample/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Dongle
      fonts:
        - asset: assets/fonts/Dongle/Dongle-Bold.ttf
        - asset: assets/fonts/Dongle/Dongle-Light.ttf
        - asset: assets/fonts/Dongle/Dongle-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
